---
title: "2010 Population Simulation"
author: "Matt Bayley, Carlos Delgado, Oki Ogbe"
date: "12/13/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include = FALSE}
library(gt)
library(tidyverse)
library(knitr)
```

# Create Birth Chunks

```{r, echo = FALSE}
draw = function(a,b,m){
  
  
  
  # if invt > m , then use the m-t transform
  
  #a-t transform
  u = runif(1)
  
  inv_t = 2*u*(-a+m)+a
  
  x1 = inv_t
  
  # if invt > m , then use the m-t transform
  
  if(inv_t>m){
    
    u = runif(1)
    
    inv_t = u*(2*(b-m))+m
    
    x1 = inv_t
  }
  
  
  return (x1)
}




###########The first population births

# fertility rates for 2010 in thousands (10-15 & 45-50 left as 1982 rate)

twenty_ten = c(0.2, 29.3, 87.3, 96.6, 82.7, 50.7, 12.6, 1.9)/1000

x0 = 1.9


# population age bins  for 10 -60  10-14,15-19......60


population_age_bins_10260 = c(20677, 20040, 21585, 21101, 19962, 20179, 20890, 22708)



# women Population vector 10 to 60

women_pop = c(10097, 10736, 10571, 10466, 9965, 10137, 10496,11499)*1000



#### loop to calculaste first year fertility ratios #######

# fertility rates distribution
b = 2.338

m = 1.957

a = 1.646

# quinial change distribution


a_z = 0

m_z = 0.3

b_z = 0.5


###### loop tro get fertility age bins
fertility_ratio = twenty_ten/x0

fertility_age_bins = rep(NA,length(fertility_ratio))


for (i in 1:length(fertility_ratio)) {
  
  fertility_i = draw(a,b,m)
  
  zt = draw(a_z,b_z,m_z)
  
  #Makes sure that the fertility rates are not 
  #too much more than the quinial chamge
  while(abs(fertility_i-x0)> zt){
    # keeps redrawing until the above condition is met
    fertility_i = draw(a,b,m)
  }
  
  
  fertility_age_bins[i] =  fertility_i*fertility_ratio[i]
  
}








# birth rates Ft in the matrix for 10 to 60
births_age_bins = women_pop*fertility_age_bins


#Ft in the matrix
Birth_rate =births_age_bins/population_age_bins_10260












######## Birth rates function in thousands######

birth_fxn = function(year) {
  twenty_ten = c(0.2, 29.3, 87.3, 96.6, 82.7, 50.7, 12.6, 1.9)/1000
  
  x0 = 1.9
  
  women_pop = c(10097, 10736, 10571, 10466, 9965, 10137, 10496,11499)*1000
  
  
  
  # fertility rates distribution
  b = 2.338

m = 1.957

a = 1.646
  
  # quinial change distribution
  
  
  a_z = 0
  
  m_z = 0.3
  
  b_z = 0.5
  
  
  
  fertility_ratio = twenty_ten/x0
  
  fertility_age_bins = rep(NA,length(fertility_ratio))
  
  
  for (i in 1:length(fertility_ratio)) {
    
    fertility_i = draw(a,b,m)
    
    zt = draw(a_z,b_z,m_z)
    
    #Makes sure that the fertility rates are not 
    #too much more than the quinial chamge
    while(abs(fertility_i-x0)> zt){
      # keeps redrawing until the above condition is met
      fertility_i = draw(a,b,m)
    }
    
    
    fertility_age_bins[i] =  fertility_i*fertility_ratio[i]
    
  }
  # birth rates Ft in the matrix
  births_age_bins = women_pop*fertility_age_bins
  
  
  # population age bins 10-14,15-19......
  
  
  population_age_bins_10260 = c(20677, 20040, 21585, 21101, 19962, 20179, 20890, 22708)
  
  #Ft in the matrix
  Birth_rate =births_age_bins/population_age_bins_10260
  
  return(Birth_rate)
}

birth_fxn(2010)
```


# Immigration

```{r, echo = FALSE}
#################### Immigration


#initial net migration

NI0 = 450000/1000000

#Immigration age bins in 1/1million
Immigration_age_bins = c(32600, 37300, 42600, 46300, 57500, 74800, 49000, 31100, 21100, 16100, 13800, 10800, 8600, 4800, 2400, 700, 300, 0, 0, 0, 0)/1000000


Immigration_ratio = Immigration_age_bins/NI0




###### net imigration age bins loop #####


#single year net immigration
a_im= .25

m_im= .45

b_im= .75

# quiniial immigration
a_im_quin = 1.25

m_im_quin = 2.25

b_im_quin = 3.75

Net_IM_age_bins = rep(NA,length(Immigration_age_bins))

#### loop to create new immigration age bins


for (i in 1:length(Immigration_age_bins)) {
  
  Net_IM_i = draw(a_im,b_im,m_im)
  
  #quinnial net immigration
  quin_im  = draw(a_im_quin, b_im_quin, m_im_quin)
  while(abs(Net_IM_i-NI0)>quin_im){
    # keeps redrawing until the above condition is met
    Net_IM_i = draw(a_im,b_im,m_im)
  }
  
  
  
  
  Net_IM_age_bins[i] =  Net_IM_i*Immigration_ratio[i]
  
  
  
  
}




######Immigration function#####

imm_fxn = function(year) {
  
  NI0 = 450000/1000000
  
  Immigration_age_bins = c(32600,37300,42600,46300,57500,74800,49000,
                           31100,21100,16100,13800,10800,8600,4800,
                           2400,700,300,0,0,0,0   ) /1000000
  
  
  Immigration_ratio = Immigration_age_bins/NI0
  #single year net immigration
  a_im= .25
  
  m_im= .45
  
  b_im= .75
  
  # quiniial immigration
  a_im_quin = 1.25
  
  m_im_quin = 2.25
  
  b_im_quin = 3.75
  
  Net_IM_age_bins = rep(NA,length(Immigration_age_bins))
  
  
  for (i in 1:length(Immigration_age_bins)) {
    
    Net_IM_i = draw(a_im,b_im,m_im)
    
    #quinnial net immigration
    quin_im  = draw(a_im_quin, b_im_quin, m_im_quin)
    while(abs(Net_IM_i-NI0)>quin_im){
      # keeps redrawing until the above condition is met
      Net_IM_i = draw(a_im,b_im,m_im)
    }
    
    
    
    
    Net_IM_age_bins[i] =  Net_IM_i*Immigration_ratio[i]
    
    
    
  }
  return(Net_IM_age_bins)
  
}

imm_fxn(1987)
```

# Get survival rate, population, leslie function and 2010's Projection


```{r, echo = FALSE}
##### Actual Population for 2010 #######

# population in thousands so each of these are millions

population_age_bins_0 = c(20201, 20348, 20677, 22040, 21585, 21101, 19962, 20179, 20890, 22708, 22298, 19664, 16817, 12435, 9278, 7317, 5743, 3620, 1448, 371, 53)



#################### first year calculations ########

# population
Ni = population_age_bins_0*1000

#net immigration
NI_i = Net_IM_age_bins*1000000


#birthrate

Ft_i = Birth_rate/1000

#   [FFFFFFF] *[Ni Ni]+ [NI_i]
#   [PPPPPPP]

########### Matrix for year 1  and year 1 calculations#######

# 1-5 ,5-9,10-14,15-19  

survive_0_1 = (1-0.006123)

survive_1_4 = (1-.001071)

survive_1_5= survive_0_1 * survive_1_4

survive_5_9 = (1-0.000573)

survive_10_14 = (1-.000708)

survive_15_19= (1-.002463)

survive_20_24 = (1-.004317)

survive_25_29 = (1-.004791)

survive_30_34 = (1-.005497)

survive_35_39 = (1-.006913)

survive_40_44 = (1-.009979)

survive_45_49 = (1-.016044)

survive_50_54 = (1-.024343)

survive_55_59 = (1-.035106)

survive_60_64 = (1-.049847)

survive_65_69 = (1-.074406)

survive_70_74 = (1-.112315)

survive_75_79 = (1-.174782)

survive_80_84 = (1-.274384)

survive_85_89 = (1-.430820)

survive_90_94 = (1-.615282)

survive_94_99= (1-.783397)

survive_over100= (1-1)


vec1 <- c(survive_1_5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0)
vec2 <- c(0,survive_5_9,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0)
vec3 <- c(0,0,survive_10_14,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0)
vec4 <- c(0,0,0,survive_15_19,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0)
vec5 <- c(0,0,0,0,survive_20_24,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0)
vec6 <- c(0,0,0,0,0,survive_25_29,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0)
vec7 <- c(0,0,0,0,0,0,survive_30_34,0,0,0,0,0,0,0,0,0,0,0,0,0,0)
vec8 <- c(0,0,0,0,0,0,0,survive_35_39,0,0,0,0,0,0,0,0,0,0,0,0,0)
vec9 <- c(0,0,0,0,0,0,0,0,survive_40_44,0,0,0,0,0,0,0,0,0,0,0,0)
vec10 <- c(0,0,0,0,0,0,0,0,0,survive_45_49,0,0,0,0,0,0,0,0,0,0,0)
vec11 <- c(0,0,0,0,0,0,0,0,0,0,survive_50_54,0,0,0,0,0,0,0,0,0,0)
vec12 <- c(0,0,0,0,0,0,0,0,0,0,0,survive_55_59,0,0,0,0,0,0,0,0,0)
vec13 <- c(0,0,0,0,0,0,0,0,0,0,0,0,survive_60_64,0,0,0,0,0,0,0,0)
vec14 <- c(0,0,0,0,0,0,0,0,0,0,0,0,0,survive_65_69,0,0,0,0,0,0,0)
vec15 <- c(0,0,0,0,0,0,0,0,0,0,0,0,0,0,survive_70_74,0,0,0,0,0,0)
vec16 <- c(0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,survive_75_79,0,0,0,0,0)
vec17 <- c(0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,survive_80_84,0,0,0,0)
vec18 <- c(0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,survive_85_89,0,0,0)
vec19 <- c(0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,survive_90_94,0,0)
vec20 <- c(0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,survive_94_99,0)
vec21 <- c(0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,survive_over100)

FT <- c(0,0,Ft_i,0,0,0,0,0,0,0,0,0,0,0)
length(FT)

### leslie matrix
LeslieMatrix <- rbind(FT,vec1,vec2,vec3,vec4,vec5,vec6,vec7,vec8,vec9,vec10,vec11,vec12,
                      vec13,vec14,vec15,vec16,vec17,vec18,vec19,vec20,vec21)


#### Ni_t each years population bina and birth  totals calculation.##
Pop0 <- LeslieMatrix%*%Ni+NI_i

head(Pop0)

## first year population
sum(Pop0)
Pop0
```


```{r, echo = FALSE}
leslie_fxn = function(year) {
  survive_0_1 = (1-0.006123)

survive_1_4 = (1-.001071)

survive_1_5= survive_0_1 * survive_1_4

survive_5_9 = (1-0.000573)

survive_10_14 = (1-.000708)

survive_15_19= (1-.002463)

survive_20_24 = (1-.004317)

survive_25_29 = (1-.004791)

survive_30_34 = (1-.005497)

survive_35_39 = (1-.006913)

survive_40_44 = (1-.009979)

survive_45_49 = (1-.016044)

survive_50_54 = (1-.024343)

survive_55_59 = (1-.035106)

survive_60_64 = (1-.049847)

survive_65_69 = (1-.074406)

survive_70_74 = (1-.112315)

survive_75_79 = (1-.174782)

survive_80_84 = (1-.274384)

survive_85_89 = (1-.274384)

survive_90_94 = (1-.274384)

survive_94_99= (1-.274384)

survive_over100= (1-.274384)

  
  vec1 <- c(survive_1_5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0)
  vec2 <- c(0,survive_5_9,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0)
  vec3 <- c(0,0,survive_10_14,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0)
  vec4 <- c(0,0,0,survive_15_19,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0)
  vec5 <- c(0,0,0,0,survive_20_24,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0)
  vec6 <- c(0,0,0,0,0,survive_25_29,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0)
  vec7 <- c(0,0,0,0,0,0,survive_30_34,0,0,0,0,0,0,0,0,0,0,0,0,0,0)
  vec8 <- c(0,0,0,0,0,0,0,survive_35_39,0,0,0,0,0,0,0,0,0,0,0,0,0)
  vec9 <- c(0,0,0,0,0,0,0,0,survive_40_44,0,0,0,0,0,0,0,0,0,0,0,0)
  vec10 <- c(0,0,0,0,0,0,0,0,0,survive_45_49,0,0,0,0,0,0,0,0,0,0,0)
  vec11 <- c(0,0,0,0,0,0,0,0,0,0,survive_50_54,0,0,0,0,0,0,0,0,0,0)
  vec12 <- c(0,0,0,0,0,0,0,0,0,0,0,survive_55_59,0,0,0,0,0,0,0,0,0)
  vec13 <- c(0,0,0,0,0,0,0,0,0,0,0,0,survive_60_64,0,0,0,0,0,0,0,0)
  vec14 <- c(0,0,0,0,0,0,0,0,0,0,0,0,0,survive_65_69,0,0,0,0,0,0,0)
  vec15 <- c(0,0,0,0,0,0,0,0,0,0,0,0,0,0,survive_70_74,0,0,0,0,0,0)
  vec16 <- c(0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,survive_75_79,0,0,0,0,0)
  vec17 <- c(0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,survive_80_84,0,0,0,0)
  vec18 <- c(0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,survive_85_89,0,0,0)
  vec19 <- c(0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,survive_90_94,0,0)
  vec20 <- c(0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,survive_94_99,0)
  vec21 <- c(0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,survive_over100)
  
  #birth function gives birthrates in thousands
  
  
  FT <- c(0,0,birth_fxn(year)/1000,0,0,0,0,0,0,0,0,0,0,0)
  length(FT)
  
  LeslieMatrix <- rbind(FT,vec1,vec2,vec3,vec4,vec5,vec6,vec7,vec8,vec9,vec10,vec11,vec12,
                        vec13,vec14,vec15,vec16,vec17,vec18,vec19,vec20,vec21)

  return(LeslieMatrix)
  }

leslie_fxn(1982)
```


# Population Projections 2010-2050

```{r}
# last year of projections.
end_year = 41
sim_num = 100
sim_num2 = 1000


## Leslie matrix use 2010s for first year because we need the
# original ratio multiplier

Leslie_Monte_list = list()

# 2010s leslie matrix to make 1983's
 
Leslie_Monte_list[[1]] =  LeslieMatrix


#sim_matrix1000 = matrix(0,sim_num2,end_year)


### iterative population age bins and fertility rate 
Ni_t_list = list()



sum(Pop0[2:22])
# adding 
Ni_t_list[[1]] = population_age_bins_0

#Save simulations in a simlength x end year long matrix
#[,j] subsets rows [i,](up and down) subsets columns(left and right)
# [same row number,j] lets you add values left to right in the same row
sim_matrix100 = matrix(sum(population_age_bins_0),sim_num,end_year)

####Immigration list

NI_t_list= list()

## populated with 1982 at first and then updated iterativley
NI_t_list[[1]] = NI_i

#Leslie matricies

leslie_list = list()


### populated with 1982 at first and then updated iterativley

leslie_list[[1]] = LeslieMatrix

deaths = rep(NA, sim_num)

added = rep(NA,end_year)

current_pop_list = list()

Immigrate_added = rep(NA,end_year)


########## begginning of loop ######

# starting in 1983 using each previous years data to update 
#the current years projections. We each set of projections in a single
# row of a matrix with dimenions simnumX endyear. 
# So rows will be endyear long
# we will simulate 1000s of these projections so the number of
#columns is sim num long


##########Simulating 100 times#################

for (i in 1:sim_num) {
  # saves a new set of projections(rows)
  for (j in 2:end_year) {
    # j starts at 2 because we need to do j-1 
    #to get the previous year erach time
    # saves a new year into a projection set(columns) 
    
    # start with 1982's populatioon age bins vector
    Ni_t =   Ni_t_list[[j-1]]
    
    #Start with 1982's leslie matrix
    leslie = leslie_list[[j-1]]
    
    #start with 1982's net immigration age bins vector
    
    NI_t = NI_t_list[[j-1]]
    
    #Get the 22x1 current population bins vector with births
    
    Ni_t1_with_births = leslie %*% Ni_t +NI_t
    
    # save births
    added[j-1] = Ni_t1_with_births[1]
    
    #remove the births column of the matrix but add the number
    # of births into the 0-5 age bin
    
     Ni_t1 = Ni_t1_with_births[2:22]
     
     Ni_t1[1] = Ni_t1[1]+ added[j-1]
     
     #save the new age bins into the age bins list
     
     Ni_t_list[[j]] = Ni_t1
     
     #save the population into a column(j) in a single projection row(i)
     
     sim_matrix100[i,j] = sum(Ni_t1)
     
     # update fertility and immigration randomly/stochasticly
     
     leslie_list[[j]] = leslie_fxn(j)
     
     NI_t_list[[j]] = imm_fxn(j) * 1000000
    
  }
}

colMeans(sim_matrix100)
```


```{r}
############## Creating Table ###################

######Creating vectors for 100 sims#########

twentyten_100 = sim_matrix100[,1]
twenty_fifteen_100 = sim_matrix100[,6]
twenty_twenty_100 = sim_matrix100[,11]
twenty_twentyfive_100 = sim_matrix100[,16]
twenty_thirty_100 = sim_matrix100[,21]
twenty_thirtyfive_100 = sim_matrix100[,26]
twenty_fourty_100 = sim_matrix100[,31]
twenty_fourtyfive_100 = sim_matrix100[,36]
twenty_fifty_100 = sim_matrix100[,41]



######Put into matrices#########

quantile100 = matrix(data = NA, nrow = 9, ncol = 100)




quantile100[1,] = twentyten_100
quantile100[2,] = twenty_fifteen_100
quantile100[3,] = twenty_twenty_100
quantile100[4,] = twenty_twentyfive_100
quantile100[5,] = twenty_thirty_100
quantile100[6,] = twenty_thirtyfive_100
quantile100[7,] = twenty_fourty_100
quantile100[8,] = twenty_fourtyfive_100
quantile100[9,] = twenty_fifty_100






quantile100t = t(quantile100)




ci_100 = apply( quantile100t, 2 , quantile , probs = c(0.025, 0.5, 0.975) , na.rm = TRUE )



sd_100 = apply(quantile100t, 2, sd, na.rm = TRUE)




tfor100 = qt(.975, 99)


standard_error = function(quantilematrix, n) {
  
  apply(quantilematrix, 2, sd, na.rm = TRUE)/sqrt(n)
}


moe100 = standard_error(quantile100t, 100) * tfor100


means100 = colMeans(quantile100t)


conf_int_matrix100 = matrix(data = NA, nrow = 3, ncol = 9)


conf_int_matrix100[1,] = means100 - moe100
conf_int_matrix100[2,] = means100
conf_int_matrix100[3,] = means100 + moe100
View(conf_int_matrix100)
sum(Pop0)
```


```{r}
###################Plots for CI's#######################

library(cowplot)
library(ggplot2)

actual_87 = 245
actual_92 = 257
actual_97 = 271
actual_02 = 287
actual_12 = 314
actual_20 = 331

actual_vec = c(245, 257, 271, 287, 314, 331)
actual_vec_trans = t(actual_vec)

conf_int_matrix100_simp = conf_int_matrix100/10000


install.packages("gt")
library(gt)
library(tidyverse)

conf_int_matrix100trans = t(conf_int_matrix100)

conf_int_matrix100trans2 = conf_int_matrix100trans/1000000


dfci = as.data.frame(conf_int_matrix100trans2[1:6,])


rowname_vec = c(1987, 1992, 1997, 2002, 2012, 2022)

dfci2 = dfci %>%
  mutate("Actual US Population" = actual_vec) %>%
  mutate("Years" = rowname_vec) %>%
  rename("Lower Bound" = "V1", "Mean" = "V2", "Upper Bound" = "V3")
  
rownames(dfci2) = c("1987", "1992", "1997", "2002", "2012", "2022")

dfci2 %>%
  gt() %>%
  tab_header(title = "Confidence Intervals vs Actual Population")
  
```






